# Define target part
export PRJ_PART = XCU200-FSGD2104-2-E

# Define target output
target: prom

export RUCKUS_DIR = $(abspath $(PWD)/../../submodules/ruckus)

# Use top level makefile
include $(RUCKUS_DIR)/system_vivado.mk
