# Define target part
export PRJ_PART = xcvu9p-fsgd2104-2-e

# Define target output
target: prom

export TOP_DIR = $(abspath $(PWD)/../../)

# export USE_XVC_DEBUG = 1

# Use top level makefile
include $(TOP_DIR)/submodules/ruckus/system_vivado.mk
