
# Define target output
target: bit

# Define target part
export PRJ_PART = XC7Z045FFG900-2

export RUCKUS_DIR = $(abspath $(PWD)/../../submodules/ruckus)

#export REMOVE_UNUSED_CODE = 1

export PRJ_VERSION = 0x00000010

#export GIT_BYPASS = 1

# Use top level makefile
include $(RUCKUS_DIR)/system_vivado.mk

